### PR TITLE
don't format EFI if it exist

### PR DESCRIPTION
**Pull request by CyrusYip**

### CODE REVIEW

**Comment by CyrusYip** [comment]
上次格式化 EFI 分区，把 Windows 启动项搞没了，头大。

**Comment by TakoTakoo** [comment]
This tutorial does not support the case of dual systems.

**Comment by CyrusYip** [comment]
For new Arch Linux users, It might be better to keep the original operating system. It might be difficult to move from Windows or macOS to Arch Linux suddenly. It takes some time to become accustomed to Arch Linux.

**Comment by ryosukeeeeee** [comment]
Time has passed for a long time and has been replied, closed.

**Pull request closed without merging**
