### PR TITLE
set low swappiness to improve responsiveness

### PR DESCRIPTION
**Pull request by CyrusYip**
Reference:

- https://wiki.archlinux.org/title/Swap#Swappiness
- https://wiki.archlinux.org/title/Swap_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E4%BA%A4%E6%8D%A2%E5%80%BC(Swappiness)

### CODE REVIEW

**Review by livrth — APPROVED** [review]

**Comment by TakoTakoo** [comment]
I don't think it is necessary to set swappiness.

**Comment by CyrusYip** [comment]
为啥没必要？RAM 不是比 swap（硬盘）快很多吗？

**Comment by TakoTakoo** [comment]
@CyrusYip Because for modern personal computers, setting swap is even redundant.

**Comment by CyrusYip** [comment]
@TakoTakoo 我一般拿来休眠，下次开机的时候就可以马上工作了。但其他时候就不太需要 swap，所以把 swappiness 调低。

**Comment by TakoTakoo** [comment]
@CyrusYip Regarding the hibernation, someone submitted a PR before, but I deleted it later because the setting was too cumbersome. At the same time, I think suspend to RAM is enough, and hibernate to swap is redundant.

**Comment by CyrusYip** [comment]
要是带着笔记本电脑出去，睡眠会继续耗电，但是休眠不会耗电。

**Comment by TakoTakoo** [comment]
@CyrusYip Regarding hibernation to swap, you can refer to arch wiki or other documents, setting of the hibernation is too cumbersome and does not make much sense, I will not add it to this document. I have already mentioned the problem you described in the document.

**Pull request closed without merging**
